### ISSUE TITLE
bug: UI flickering on save all files `:wa<cr>`

### ISSUE THREAD

**Issue by radvil** [folke/noice.nvim#658] opened 2023-11-22 15:07 UTC
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-616+g203181234

### Operating system/version

Arc Linux

### Describe the bug

With noice.nvim enabled, if i hit save all files that are currently opened and modified, annoying UI flickering happened

## how to reproduce

- Enable noice.nvim
- Open and modify some files, dont save them yet
- hit save all `:wa`
- Annoying UI flickering happened
- Disable noice.nvim
- retry previous steps
- no UI flickering happened this time

### Expected Behavior

should not be flickering, because that's annoying...
I wanna disable noice.nvim but i found it very helpful to redirect any messages like `no information available` on lsp hover

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by brianmego** [comment] 2024-01-22 02:43
Do you happen to be running inside of a multiplexer like tmux or zellij perchance? I'm noticing the same behavior, but only inside of zellij.

**Comment by folke** [comment] 2024-01-22 07:49
Could be due to using a multiplexer, or could also be due to some things inside NEovim.

Closing, since this is not really something I can control from noice

**Closed by folke** 2024-01-22 07:49 UTC
Labels: bug

**Comment by brianmego** [comment] 2024-01-22 12:56
I agree this is unlikely noice. I am interested in the answer from @radvil if possible. I'm tracking a parallel but in zellij and seeing if there's a shared root cause.

**Comment by rbingham** [comment] 2024-02-07 19:58
@brianmego I believe that I have the same issue with Zellij. When a notification pops up while using Zellij the screen flickers. While outside Zellij it doesn't happen

**Comment by radvil** [comment] 2024-02-10 16:04
I've been trying this by not using multiplexer, I'm using kitty terminal. and it still happened for me. Do you want me to include a video @folke ?
