### ISSUE TITLE
Lualine disappears after resizing window

### ISSUE THREAD

**Issue by nick4tech** [folke/noice.nvim#33] opened 2022-10-06 14:11 UTC
**Describe the bug**
If I resize the pane of the terminal where vim is running in, lualine disappears. It only happens while noice is enabled.

**Which version of Neovim are you using?**
0.80

**To Reproduce**
run noice and lualine, then resize the terminal window / pane.

**Expected Behavior**
Window is resized and lualine is till visible at the bottom

**Screenshots**
![image](https://user-images.githubusercontent.com/6836442/194335616-7bddca37-1823-4ba7-ac02-bdc2b69296c3.png)

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
Log comes here
</pre>
</details>

**Comment by cscovino** [comment] 2022-10-07 18:26
I have the same issue with iterm2

https://user-images.githubusercontent.com/9748855/194624588-d3ce3477-ae80-4cf8-8132-bfc7867ed257.mov

and with warp is something similar

https://user-images.githubusercontent.com/9748855/194624703-13622577-e622-49ed-ac7c-f83676b321b1.mov

The noice log is empty.

**Comment by folke** [comment] 2022-10-09 07:56
Can't reproduce. Are you sure this is a Noice issue and not a `cmdheight=0` issue? Please test wthout noice and set cmdheight=0. Feels like a Neovim issue.

**Comment by folke** [comment] 2022-10-09 09:08
Does the same happen with `minimal.lua`? https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by JonasUJ** [comment] 2022-10-09 18:27
I'm having the same problem. Here's minimal.lua with lualine in WSL and neovim v0.8.0.

https://user-images.githubusercontent.com/21989288/194773393-c4399417-713f-42de-a100-0085e92d1df9.mp4

**Comment by cscovino** [comment] 2022-10-11 15:10
> Can't reproduce. Are you sure this is a Noice issue and not a `cmdheight=0` issue? Please test without noice and set cmdheight=0. Feels like a Neovim issue.

It works ok. The issue is only when I configure noice.

**Comment by folke** [comment] 2022-10-14 12:52
That's so weird. I can't repro with Alacritty and minimal.lua

**Comment by kierun** [comment] 2022-10-14 12:56
What version of `neovim` are you running? Is it the latest `main` branch?

**Comment by folke** [comment] 2022-10-14 12:57
for me, it works both on stable and nightly

**Comment by Shougo** [comment] 2022-10-14 12:59
Hm...

I will test it later.

**Comment by folke** [comment] 2022-10-14 13:00
If anyone wants to easily switch between nightly/stable or older versions, I can highly recommend https://github.com/MordechaiHadad/bob

**Comment by kierun** [comment] 2022-10-14 13:20
@folke 
> If anyone wants to easily switch between nightly/stable or older versions, I can highly recommend https://github.com/MordechaiHadad/bob

This is a really good tool! Thank you.

@Shougo 
> You should use neovim HEAD.

Living on the bleeding edge! The 'nightly' (as per bob) does fix the issue in both Alacritty and neovim-qt.

**Comment by Shougo** [comment] 2022-10-14 13:24
OK.  So I don't need to test the issue..

**Comment by folke** [comment] 2022-10-14 13:43
Great 🙂 Closing this, since its already fixed on nightly

**Closed** 2022-10-14 13:43 UTC
