### ISSUE TITLE
split window closes on match

### ISSUE THREAD

**Issue by duarm** [folke/noice.nvim#198] opened 2022-11-06 16:18 UTC
**Describe the bug**
When opening a message in a split, e.g. highlights, if I search with /, once I press enter to match, the split closes

**Which version of Neovim are you using?**
0.9.0-dev

**To Reproduce**
1. Open a message on a split, e.g. highlights
2. Search something with /
3. Press ENTER

**Expected Behavior**
When I press ENTER, the text is matched and the split does not close.

**Comment by folke** [comment] 2022-11-07 08:18
Please provide a minimal.lua https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue.

`close.events = {"BufLeave"}` is only set by default for `config.views.popup`, not splits.
Splits only close on `q`.

**Comment by gennaro-tedesco** [comment] 2022-11-09 21:28
I observed the same behaviour (using `minimal.lua`); in particular, however, only for splits that open invoking `highlights/map/set` functions. 

I presume the reason is that such interfaces are not "searchable" even in standard (un-configured) vim, namely if you open the `:highlight` (likewise `:map`, `:set`) view and `/`, the search is not responsive (vim does not allow you to search those views). Perhaps the behaviour translates into Noice into the popup/split closing as `/` is an un-recognised key.

**Comment by folke** [comment] 2022-11-09 21:31
@gennaro-tedesco thank you for your comment. I can indeed reproduce it now with `:hi`.

Those views are definately searchable, nothing special about those buffers.

Will look into it

**Comment by folke** [comment] 2022-11-09 21:36
So the problem is that doing the search, actually clears the current active messages, which means the split will be cleared. Related to https://github.com/folke/noice.nvim/issues/164

That's something I'm planning to fix/change soon, but for now, the best easiest way to work around it, is doing `:Noice last` after for example `:hi`. That will open the last command in a popup where you can search

**Closed** 2022-11-10 17:39 UTC
Labels: bug
