### ISSUE TITLE
bug: `cmdline.view` overwrites `cmdline.format.search_down.view` ~50% of the time.

### ISSUE THREAD

**Issue by chrisgrieser** [folke/noice.nvim#841] opened 2024-06-07 01:06 UTC
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

macOS 14.4.1 (arm)

### Describe the bug

So this is a weird one.

This config results in the `/` search sometimes using the cmdline, and _sometimes_ using the `cmdline_popup`. Happens about every other time.
```lua
cmdline = {
	view = "cmdline_popup",
	format = {
		search_down = { view = "cmdline" },
	},
},
```

And with this config, the search *always* uses the cmdline. 
```lua
cmdline = {
	view = "cmdline",
	format = {
		search_down = { view = "cmdline" },
	},
},
```

My assumption is that `cmdline.view` apparently overwrites `cmdline.format.search_down.view` based on a certain race condition?
Also, the problem does not seem to occur for `cmdline.format.cmdline.view` and the others. (Though I haven't tried every possible permutation).

### Steps To Reproduce

1. Use the config
2. restart nvim
3. press `/`

Repeat 2. and 3. multiple times; the view used is not consistent. 

<img alt="Showcase" width=70% src="https://github.com/folke/noice.nvim/assets/73286100/1282e92c-3374-4033-a3b9-df0b759852a8">

### Expected Behavior

The `cmdline.format.search_down.view` setting should work, consistently.

### Repro

```Lua
local plugins = {
	{
		"folke/noice.nvim",
		dependencies = "MunifTanjim/nui.nvim",
		opts = {
			cmdline = {
				view = "cmdline_popup",
				format = {
					search_down = { view = "cmdline" },
				},
			},
			-- cmdline = {
			-- 	view = "cmdline",
			-- 	format = {
			-- 		search_down = { view = "cmdline" },
			-- 	},
			-- },
		},
	},
}

--------------------------------------------------------------------------------

for _, name in ipairs { "config", "data", "state", "cache" } do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = "/tmp/nvim-debug/" .. name
end

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if vim.uv.fs_stat(lazypath) == nil then
	local lazyrepo = "https://github.com/folke/lazy.nvim"
	vim.system({ "git", "clone", "--filter=blob:none", lazyrepo, "--branch=stable", lazypath }):wait()
end
vim.opt.runtimepath:prepend(lazypath)
require("lazy").setup(plugins)
```

**Comment by b0ae989c** [comment] 2024-06-07 01:17
Yes I can confirm this issue also appears on macOS 14.5 with NVIM v0.10.0 (LuaJIT 2.1.1716656478).

**Comment by b0ae989c** [comment] 2024-06-07 01:49
Is this related to the change of `vim.deepcopy` in https://github.com/neovim/neovim/commit/3734519e3b4ba1bf19ca772104170b0ef776be46 ? Since it's in cmdline setup
https://github.com/folke/noice.nvim/blob/29c7f030b0920e2f17263a9ab8742cde144b9140/lua/noice/config/cmdline.lua#L42

**Comment by folke** [comment] 2024-06-07 04:20
Might be!

Would be great f you could check it's fixed with passing noref = true and make a PR if that fixes it.

**Comment by folke** [comment] 2024-06-07 07:37
I found the issue. It only happens for `search`.
Add `search_up` to fix it.
```lua
        format = {
          search_down = {
            view = "cmdline",
          },
          search_up = {
            view = "cmdline",
          },
        },
```

Reason is that for search, the message kind is for both just `search`, so the cmdline will basically switch between two at random.

Will see to make a proper fix

**Closed** 2024-06-07 07:52 UTC
Labels: bug

**Comment by chrisgrieser** [comment] 2024-06-07 13:16
works fine now, thank you!
