### ISSUE TITLE
bug: hlslens configuration makes `n` add `<cr>`

### ISSUE THREAD

**Issue by luiz00martins** [folke/noice.nvim#642] opened 2023-10-29 10:20 UTC
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-bc850ba

### Operating system/version

Windows 10 Home 19045.3570

### Describe the bug

Using the default configuration for [nvim-hlslens](https://github.com/kevinhwang91/nvim-hlslens), if a search made with `n`/`N` fails (no match is found), an extraneous `<cr>` gets added in the cursor.

This does not happen with just nvim-hlslens, only when Noice is also present.

https://github.com/folke/noice.nvim/assets/43142209/aaf9f1f7-6b52-4a44-ab35-0531c06186be

_See https://github.com/kevinhwang91/nvim-hlslens/issues/65_

### Steps To Reproduce

1. Install Noice
2. Install nvim-hlslens, and set up its recommended `n`/`N` mappings. That is:
```lua
vim.api.nvim_set_keymap('n', 'n',
    [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
vim.api.nvim_set_keymap('n', 'N',
    [[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
```
3. Enter a buffer, and search for something that does not exist in the buffer
4. Press `n`/`N`

If you remove Noice, pressing `n`/`N` won't present the wrong behaviour.

### Expected Behavior

Nothing be added on the buffer upon failure.

**Comment by folke** [comment] 2023-10-29 13:12
Duplicate of https://github.com/folke/noice.nvim/issues/643

**Closed by folke** 2023-10-29 13:12 UTC
Labels: bug
