### ISSUE TITLE
Issue with interaction with nui?

### ISSUE THREAD

**Issue by konstantinos-null** [folke/noice.nvim#72] opened 2022-10-16 21:30 UTC
**Describe the bug**
After upgrading neovim, nui and noice I am having issues with the dropdown menu when running a command. 

**Which version of Neovim are you using?**
NVIM v0.9.0-dev-82-g0ef6aaa3a

Latest working plugin versions
Plug 'MunifTanjim/nui.nvim', { 'commit': 'cc76e6ff13629b18d3dedfadd4f52e35ff085700' }                           
Plug 'rcarriga/nvim-notify'                                                                                     
Plug 'folke/noice.nvim', { 'commit': '312ac20daeae1ba73c300671bbf8d405419a33ef'}  

**To Reproduce**
1. Use specific versions used above to see the expected result
2. Use latest
3. Ping me if I can provide more info or correct anything that is not clear enough!

**Expected Behavior**

**Screenshots**

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
paste log here
</pre>
</details>

![Screenshot from 2022-10-17 00-19-56](https://user-images.githubusercontent.com/96949624/196058874-1d99b57a-4de3-4666-9559-6aac324c3b3c.png) Problematic(?)
![Screenshot from 2022-10-17 00-23-16](https://user-images.githubusercontent.com/96949624/196058983-e6ab0340-b570-4158-b627-7652154a6308.png) Expected.

[noice.log](https://github.com/folke/noice.nvim/files/9795721/noice.log)

**Comment by folke** [comment] 2022-10-16 21:46
What is wrong in the images exactly? What's the part you're expecting? Also, what image is the wrong one and which one is how it should look?

**Comment by folke** [comment] 2022-10-16 21:47
No need to use an older version. Use the latest version. Post a screenshot. And tell me what's wrong in the image

**Comment by folke** [comment] 2022-10-16 21:51
Can you also post your config? According to the log file, you're not using the default config.

**Comment by konstantinos-null** [comment] 2022-10-16 21:57
Below is the configuration related to noice, although on my laptop a simple noice.setup({}) is producing the same error.
`❯ cat lua/user/noice.lua                                                                                            
local status_ok, noice = pcall(require, "noice")                                                                    
if not status_ok then                                                                                               
    print("Something went wrong with noice")                                                                        
    return                                                                                                          
end                                                                                                                 
                                                                                                                    
noice.setup({                                                                                                       
  views = {                                                                                                         
    cmdline_popup = {                                                                                               
        border = "none",                                                                                            
        padding = { 2, 3},                                                                                          
    },                                                                                                              
  },                                                                                                                
  filter_options = {},                                                                                              
    win_options = {                                                                                                 
        winblend = 10,                                                                                              
        winhighlight = {                                                                                            
            Normal = "Normal",                                                                                      
            FloatBorder = "SpecialChar"
        },
    },
})`
As far as the screenshots are concerned, the second one show a different bar when cycling through the options(on v:lua) and that is my expected behavior so we know where we are in came the cmdline_popup is not visible. The first screenshot does not highlight the current option on the menu.

**Comment by folke** [comment] 2022-10-16 22:08
So the first screenshot is from the latest noice version?

**Comment by konstantinos-null** [comment] 2022-10-16 22:10
> So the first screenshot is from the latest noice version?

Yes, correct, the pinned nui version but latest noice.

**Comment by folke** [comment] 2022-10-17 06:17
I can't reproduce this. Please try with the minimal.lua https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by folke** [comment] 2022-10-17 06:28
I think I figured it out. Your colorscheme is probably loading after Noice. 

I'll see if I can fix it so it also works in that case.

**Comment by folke** [comment] 2022-10-17 06:38
Should be fixed now! Do let me know if you still see something that's not right. But with the minimal.lua then.

**Closed** 2022-10-17 06:38 UTC
Labels: bug

**Comment by konstantinos-null** [comment] 2022-10-17 07:52
Oh man, that was really fast! :grimacing: 
Works as before, correct! Thanks for the awesome work and plugins! :1st_place_medal:
