### ISSUE TITLE
Not able to navigate to all Items in the Command Completion drop down menu while vim-sleuth is active 

### ISSUE THREAD

**Issue by Shinzu** [folke/noice.nvim#139] opened 2022-10-27 13:25 UTC
**Describe the bug**
While the `tpope/vim-sleuth` plugin is loaded im not able the navigate through the items in the command completion drop down menu. with `Tab` or `S-Tab` im only able to navigate through the 1st 2 item or 2 last items. 

**Which version of Neovim are you using?**
```
❯ vim --version
NVIM v0.9.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-3xACQl/neovim-0.9.0~ubuntu1+git202210241433-1248c1266-333b5866f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-3xACQl/neovim-0.9.0~ubuntu1+git202210241433-1248c1266-333b5866f/build/cmake.config -I/build/neovim-3xACQl/neovim-0.9.0~ubuntu1+git202210241433-1248c1266-333b5866f/src -I/build/neovim-3xACQl/neovim-0.9.0~ubuntu1+git202210241433-1248c1266-333b5866f/.deps/usr/include -I/usr/include -I/build/neovim-3xACQl/neovim-0.9.0~ubuntu1+git202210241433-1248c1266-333b5866f/build/src/nvim/auto -I/build/neovim-3xACQl/neovim-0.9.0~ubuntu1+git202210241433-1248c1266-333b5866f/build/include
Compiled by buildd@lcy02-amd64-001

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**To Reproduce**
1. add `tpope/vim-sleuth` to minimal.lua(the one from the wiki)
2. start neovim with this lua
3. enter command mode and enter `Pack` and hit `Tab` and try to navigate to eg PackerStatus

**Expected Behavior**
I can navigate through all items in the list

**Screenshots**
![image](https://user-images.githubusercontent.com/1894476/198296102-952f7310-2efe-400b-a35b-f86b5fe25d27.png)
![image](https://user-images.githubusercontent.com/1894476/198296290-f0693dda-a4f1-4c31-85a2-6edd5ad5f6ba.png)

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>

Thu 27 Oct 2022 01:56:19 PM CEST
...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:33: module 'telescope' not found:
	no field package.preload['telescope']
	no file './telescope.lua'
	no file '/usr/share/luajit-2.1.0-beta3/telescope.lua'
	no file '/usr/local/share/lua/5.1/telescope.lua'
	no file '/usr/local/share/lua/5.1/telescope/init.lua'
	no file '/usr/share/lua/5.1/telescope.lua'
	no file '/usr/share/lua/5.1/telescope/init.lua'
	no file '/home/mwyrsch/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope.lua'
	no file '/home/mwyrsch/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope/init.lua'
	no file '/home/mwyrsch/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope.lua'
	no file '/home/mwyrsch/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope/init.lua'
	no file './telescope.so'
	no file '/usr/local/lib/lua/5.1/telescope.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/telescope.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/mwyrsch/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/telescope.so'

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:140: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:139>
	[C]: in function 'require'
	...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:33: in function 'setup'
	...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:82: in function 'notify'
	.../packer/opt/noice.nvim/lua/noice/view/backend/notify.lua:165: in function '_notify'
	.../packer/opt/noice.nvim/lua/noice/view/backend/notify.lua:194: in function <.../packer/opt/noice.nvim/lua/noice/view/backend/notify.lua:172>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:123: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:118: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:77>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:34: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

</pre>
</details>
Logs seems not related, but these are the only items in there

**Comment by folke** [comment] 2022-10-27 14:30
I have no idea what's causing this. It seems that vim-sleuth is messing with the noice buffers, which it shouldn't.

Looking at the documentation, you should be able to do:

```vim
let g:sleuth_noice_heuristics = 0
```

Closing this. Again, other plugins shouldn't mess with Noice buffers

**Closed by folke** 2022-10-27 14:30 UTC
Labels: bug

**Comment by Shinzu** [comment] 2022-10-27 14:44
thx for clarifying

**Comment by bigardone** [comment] 2022-10-30 08:36
👋🏼 Hello! I just installed Noice, and I'm facing the same issue. I can only navigate through the first two options of the command's popup using TAB. However, I don't use `vim-sleuth`, and Noice's logs are empty. How can I gather more info to fix the issue? Thanks in advance 🙌🏼 

https://user-images.githubusercontent.com/1090272/198869426-af525eca-d535-4f60-b7c3-5ba6cb068ef2.mov

**Comment by ofseed** [comment] 2022-10-30 08:40
It's maybe not be caused by vim-sleuth. I've been using vim-sleuth, but I never face this issue,
although I don't `let g:sleuth_noice_heuristics = 0` before.

**Comment by folke** [comment] 2022-10-30 09:28
@ofseed i set that in noice now, so should be fine

**Comment by bigardone** [comment] 2022-10-31 05:45
@folke, should I open a new issue detailing my case?
