### ISSUE TITLE
bug: mini does not show a message after two times

### ISSUE THREAD

**Issue by ilan-schemoul** [folke/noice.nvim#969] opened 2024-10-13 16:49 UTC
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-965+gfb74fd295 Build type: RelWithDebInfo LuaJIT 2.1.1727870382

### Operating system/version

WSL ubuntu

### Describe the bug

do \<space>F three times in a row. The third times nothing appears anymore.
A workaround is typing ":" to show popupmenu then echo filename works again.
After debugging I think the culprit is in lua/noice/ui/init.lua M.enable
```lua
    if Manager.tick() > tick then
```
The condition if true the first two times and false the third.
Note that the problem is only with the backend mini, not with notify. But the bug doesn't seem to be in mini's implem. It just that I think notify, like popupmenu when typing ":", must increase tick (I'm not sure) ?
Note:
It took me *many* hours of debugging. I will give my two cents: I think that a lot of small functions calling other functions, a lot of abstractions, a *ton* of dynamic dispatch makes very hard to understand the code as an outsider. To understand a bug you have to understand what calls what, what modifies what data etc. if you're not the person who wrote the code then you don't know the abstractions very well and you struggle a lot to understand what's going on.
So it's just my 2 cents which can be ignored I just felt like maybe a bit less abstractions can help.

### Steps To Reproduce

See above

### Expected Behavior

Can show more than two times notification with mini

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

vim.keymap.set("n", "<space>F", "<cmd>echo \"de\"<cr>")

require("lazy.minit").repro({
  spec = {
  -- "folke/noice.nvim",
  dir = "~/code/forks/noice.nvim",
  event = "VimEnter",
  opts = {
    messages = {
      enabled = true, -- enables the Noice messages UI
      -- view_error = "notify",
      -- view_warn = "notify", -- view for warnings
      view = "mini", -- default view for messages
      -- enabled = true,
    },
  },
  dependencies = {
    "MunifTanjim/nui.nvim",
    {
      "rcarriga/nvim-notify",
      opts = {
        fps = 2,
      },
    },
  },
  },
})
```

**Comment by folke** [comment] 2024-11-17 19:11
This is not possible to fix for now.
Maybe on nightly, need to check again.

The problem is that Neovim spams `msg_show` events over and over again for the same event due to redraws.
To fix this, Noice checks if the last message is the same and discards it in that case.
If I would not do that, then performance of Noice would be terrible since there's a lot of potential redraw loops bound to happen that way.

**Comment by ilan-schemoul** [comment] 2024-11-18 08:18
Then I wish I could customize that limit of similar messages being shown. Could we add that as an hidden option ?

**Comment by folke** [comment] 2024-11-18 08:27
There's no way to tell.
If you'd set that limit to 3 for example then you would simply see **every** message 3 times.
So no, not an option and like I said this has to be fixed in core.

**Comment by folke** [comment] 2024-11-18 19:50
Upstream issue: https://github.com/neovim/neovim/issues/20416

**Closed by folke** 2024-11-18 19:50 UTC
Labels: bug, upstream

**Comment by ilan-schemoul** [comment] 2024-11-19 13:55
> Currently I just discard msg_show events if they're the same as the last one, but this also means if you echo the same message twice, Noice will only show it once.

Well I can see a message twice, everytime, but never a third time. Like if you do \<leader>f one time you see one message (ok), a second time you see a second message (ok), a third time I don't see anything (ko).
The expect behaviour you describe indicate I should not see any similar message two times in a row or am I mistaken
