### ISSUE TITLE
bug: Cursor jumps in cmdline - 4.5.0

### ISSUE THREAD

**Issue by xbladesub** [folke/noice.nvim#923] opened 2024-07-28 04:10 UTC
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1 Release

### Operating system/version

MacOS 14.5

### Describe the bug

Open cmdline - cursor jumps by itself

### Steps To Reproduce

open cmdline 

check cursor:

https://github.com/user-attachments/assets/336d6bf1-a9d4-417a-a304-7bbea89ecf0d

### Expected Behavior

Expected cursor doesn't jump

https://github.com/neovide/neovide/issues/2735#issuecomment-2254256173

**Comment by chrisgrieser** [comment] 2024-07-28 09:33
Have the same issue. Can repro with this minimal config + using neovide:
```lua
local spec = {
	{
		"folke/noice.nvim",
		dependencies = { "MunifTanjim/nui.nvim", "rcarriga/nvim-notify" },
		opts = true,
	},
}
--------------------------------------------------------------------------------
vim.env.LAZY_STDPATH = "/tmp/nvim-repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
require("lazy.minit").repro { spec = spec }
```

**Comment by SuXYIO** [comment] 2024-07-29 04:10
Same issue.

**Comment by JustBarnt** [comment] 2024-07-29 10:37
Same issue here. I just reverted back to V4.4.7 until Folke returns from his vacation :)

**Comment by johnend** [comment] 2024-07-30 20:57
Yep, flickering also visible in terminal (using Wezterm). Everything still works fine but is a little off-putting.

**Comment by GitMurf** [comment] 2024-07-31 20:12
I can confirm that with cmdline with noice I get the constant flicker of the cursor in the cmdline box but Search (which has the box in same location) does NOT have the flicker.

As others said above, downgrading to v4.4.7 fixed it for me.

**Comment by augustocdias** [comment] 2024-07-31 20:18
For me it only happens when I have more than 1 tab open. It also happens on 4.4.7

**Comment by leaysgur** [comment] 2024-08-01 00:43
Same here but without using Neovide.

In my case, disable `vim.o.autochdir` fixes blinking. 🤔 

```lua
﻿﻿﻿local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim.git"
	vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- ⁉️
vim.o.autochdir = true

require("lazy").setup({
	{
		"folke/noice.nvim",
		-- Workaround...
		-- version = "4.4.7",
		dependencies = { "MunifTanjim/nui.nvim" },
		opts = {},
		event = "VeryLazy",
	},
})
```

**Comment by thohnb** [comment] 2024-08-04 15:34
Thanks you ! 
I have same error, but when downgrade to **4.4.7** it fixed it

**Comment by sebastianzehner** [comment] 2024-08-05 21:53
When I open the Cmdline popup there are two cursors visible. One in the document and one in the Cmdline popup. They both flashing as wild and than I downgraded to version 4.4.7. It fixed it. The cursor in the document is now not visible and the cursor in the Cmdline popup is not flashing. Perfect and thank you! Maybe the next update will fix this issue?

**Comment by sineptic** [comment] 2024-08-07 12:45
I open VERY [similar issue](https://github.com/rcarriga/nvim-notify/issues/273) for notify plugin. We found that if in notify config set `stages="static"` this problem doesn't occurs. Is there some similar options for noice? This problem like other, that I mentioned (for me) occurs in zellij, but without it works fine.

**Comment by Vortigern-The-Grey** [comment] 2024-08-10 03:27
From my testing, this issue only occurs on Windows Terminal in specific. Afaik, Tabby, Hyper and Alacritty on windows all are fine, and don't suffer from this issue.

**Comment by emretuna** [comment] 2024-08-10 10:58
moving to 4.4.7 fixed the issue for me too.

**Comment by sineptic** [comment] 2024-08-10 13:38
> Alacritty on windows all are fine, and don't suffer from this issue.

With Alacritty on Linux I have problem. And even with all "view" options, except virtualtext(lol).

**Comment by BElluu** [comment] 2024-08-11 09:40
I have similar effect on Windows 10 - look at mentioned issue about blinking cursor.
On Linux(Ubuntu or NixOS) everything is ok.

**Comment by Vortigern-The-Grey** [comment] 2024-08-12 19:53
Pretty sure this is cause by commit 1698725.

**Comment by dinhlongviolin1** [comment] 2024-08-19 12:14
I reverted to 4.4.7 from 4.5.0. No more flickering. Hope this will be fixed soon!

**Comment by piz-ewing** [comment] 2024-08-22 02:58
> Pretty sure this is caused by commit [1698725](https://github.com/folke/noice.nvim/commit/1698725a663aca56bcd07a0e405bc441a5f6613b).

I’ve read and tried to fix it (#937 ), but I’m not sure if it works for others.

**Comment by vricop** [comment] 2024-08-26 06:43
> I open VERY [similar issue](https://github.com/rcarriga/nvim-notify/issues/273) for notify plugin. We discover that if in notify config set `stages="static"` this problem doesn't occurs. Is there some similar options for noice? This problem like other, that I mentioned (for me) occurs in zellij, but without it works fine.

Confirmed, it happens under zellij. If I open neovim normally it works fine.

I doesn't matter if I use v `4.4.7` or the latest version. I'm also convinced it has something to do with `nvim-notify`. If I delete `nvim-notify` as a dependency the bug is gone.

**Comment by tmeusburger** [comment] 2024-08-26 06:56
Also encountering the issue with

OS: Mac
Terminal: iTerm2

**Comment by vricop** [comment] 2024-08-26 12:27
As others pointed out, some users are reporting the same bug in nvim-notify. I’ll try to apply the workaround suggested in their issues. If it does work I’ll let you know.

**Comment by JustBarnt** [comment] 2024-08-26 12:45
Hmmm. Interesting that a change in here brings out a bug that exists in `nvim-notify`. I'll update to 4.5.0 again as well and disable `nvim-notify` and see if I can get the same results as well on Windows.

**Comment by vricop** [comment] 2024-08-26 12:55
> Hmmm. Interesting that a change in here brings out a bug that exists in `nvim-notify`. I'll update to 4.5.0 again as well and disable `nvim-notify` and see if I can get the same results as well on Windows.

It’s probably the zellij + nvim-notify combo causing it.

I’m going to test it this eve

**Comment by vricop** [comment] 2024-08-26 13:20
Got it working!

- Os: macOS Sonoma 15.6.1
- Terminal: iTerm2
- Mutiplexer: zellij

```lua
-- Noice config
return {
  'folke/noice.nvim',
  event = 'VeryLazy',
  enabled = enable_plugins.noice,
  dependencies = { 'MunifTanjim/nui.nvim' },
  opts = {
    cmdline = {
      format = {
        cmdline = {
          icon = [[ ]],
        },
        search_down = {
          icon = [[ 󰶡]],
        },
        search_up = {
          icon = [[ 󰶣]],
        },
        help = {
          icon = [[󰋗 ]],
        },
      },
    },
  },
}
```

```
-- Notify config
return {
  'rcarriga/nvim-notify',
  enabled = enable_plugins.notify,
  opts = {
    stages = 'static',
    icons = {
      ERROR = [[ ]],
      WARN = [[ ]],
      INFO = [[ ]],
      BUG = [[ ]]
    },
  },
}
```

**Comment by JustBarnt** [comment] 2024-08-26 13:29
Hm. I'm not sure it's only `Zellij` it could have its own underlying issue that isn't playing nicely in general, because I disabled `nvim-notify` and updated `noice` back to v4.5.0 and I still get the flickering. Both in Wezterm, Windows terminal and Neovide. It's weird that for Mac Users it seems to be an issue with `nvim-notify` though.

**Comment by vricop** [comment] 2024-08-26 13:36
> Hm. I'm not sure it's only `Zellij` it could have its own underlying issue that isn't playing nicely in general, because I disabled `nvim-notify` and updated `noice` back to v4.5.0 and I still get the flickering. Both in Wezterm, Windows terminal and Neovide. It's weird that for Mac Users it seems to be an issue with `nvim-notify` though.

Neovide? have you tried from the terminal? just in case...

**Comment by JustBarnt** [comment] 2024-08-26 13:37
@vricop Yea, I have that was why I had mentioned I still saw the issue without `nvim-notify` in Wezterm and Windows terminal as well.

**Comment by vricop** [comment] 2024-08-26 13:44
> Hm. I'm not sure it's only `Zellij` it could have its own underlying issue that isn't playing nicely in general, because I disabled `nvim-notify` and updated `noice` back to v4.5.0 and I still get the flickering. Both in Wezterm, Windows terminal and Neovide. It's weird that for Mac Users it seems to be an issue with `nvim-notify` though.

That's weird!

**Comment by vricop** [comment] 2024-08-27 15:11
Today I find out the cursor is still jumping. With a different (less annoying) behavior.

And again only inside zellij. I’ll just disable nvim-notify by now.

**Comment by vricop** [comment] 2024-08-27 15:14
Some tmux users are reporting the same bug in nvim-notify issues.

**Comment by Vortigern-The-Grey** [comment] 2024-08-27 19:08
Until Folke gets back, I could fork noice.nvim and roll back 1698725.

**Comment by vricop** [comment] 2024-08-29 08:58
> Pretty sure this is caused by commit [1698725](https://github.com/folke/noice.nvim/commit/1698725a663aca56bcd07a0e405bc441a5f6613b).

Wouldn’t be easier to config lazy package manager to install the plugin with the commit hash prior to the commit with the breaking change?

**Comment by jsonMartin** [comment] 2024-09-02 03:30
> > Pretty sure this is caused by commit [1698725](https://github.com/folke/noice.nvim/commit/1698725a663aca56bcd07a0e405bc441a5f6613b).
> 
> Wouldn’t be easier to config lazy package manager to install the plugin with the commit hash prior to the commit with the breaking change? `d9328ef`

Thanks for this suggestion. Doing this fixed this flickering issue I'm also having with `iTerm2`, `zellij`, and `LazyVim`.

Here's the code working snippet for LazyVim I added to `~/.config/nvim/lua/plugins/plugins.lua`

```
{
    "folke/noice.nvim",
    commit = "d9328ef",
},
```

**Comment by zmre** [comment] 2024-09-11 17:10
Just a note that I tried some of the fixes in here including setting nvim-notify `stages = "static"` and setting `vim.o.autochdir = true` and none of those worked for me.  I see the problem primarily in Neovide, but the rate of cursor flying is intense.  I've also reverted to the earlier version of Noice for now.

**Comment by folke** [comment] 2024-09-18 06:42
This is not a noice bug. Noice uses ui_attach and shows the cmdline in a floating window.
That floating window used to show a fake cursor. The new noice version shows the actual correct cursor position since we can now show this using `_nvim_redraw`.

The flickering is something that should be fixed in Neovide, not Noice...

**Closed by folke** 2024-09-18 06:42 UTC
Labels: bug, wontfix

**Comment by Riddlerrr** [comment] 2024-09-18 07:14
Related issue in neovide https://github.com/neovide/neovide/issues/2206

**Comment by radlinskii** [comment] 2024-09-18 08:45
But I have this problem using noice.nvim 4.5.0 in Windows Terminal in vanilla NeoVim 0.10.1 - I'm not using Neovide.
The issue is not there when using version 4.4.7.

**Comment by JustBarnt** [comment] 2024-09-18 11:15
Just to show here are two gifs on the latest Neovim nightly
```bash
Neovim Version:
NVIM v0.11.0-dev-783+g0ade8fed1
Build type: RelWithDebInfo
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more

Windows 11
OS BUILD: 22631

Wezterm Build: wezterm 20240812-215703-30345b36
```

Noice v4.5.0
![Noice-4_5_0](https://github.com/user-attachments/assets/a41a938a-799e-48cf-8dcc-c2a1fdaca67f)


Noice v4.4.7
![Noice-4_4_7](https://github.com/user-attachments/assets/e6b73c4d-e3dd-4b73-ab14-776fc28b418b)

**Comment by folke** [comment] 2024-09-18 12:41
If you want me to further investigate this, then please open a new issue with a working repro using a recent Neovim Nightly so I can reproduce it.

As I told before, I don't see that issue anywhere.

**Comment by GitMurf** [comment] 2024-09-18 19:29
FYI for others here this has been fixed in 4.5.1 here: https://github.com/folke/noice.nvim/commit/c1ba80ccf6b3bd8c7fc88fe2e61085131d44ad65

**Comment by damingerdai** [comment] 2025-05-14 14:19
I also meet this issue in iterm2 with neovim 0.11.1

**Comment by damingerdai** [comment] 2025-05-15 14:30
tihs bug only happend on iterm2 with no-fullscreen. it even work in tmux with iterm2. I don't know how to fix.

**Comment by cjcodes** [comment] 2025-05-21 14:53
> tihs bug only happend on iterm2 with no-fullscreen. it even work in tmux with iterm2. I don't know how to fix.

@damingerdai I fixed this for myself in iterm2 by disabling session-initiated window resizing (Settings > Profiles > [my profile] > Terminal > "Disable session-initiated window resizing" [checked]). It also fixed a bunch of other window-flashing bugs I was running into.

**Comment by damingerdai** [comment] 2025-05-22 13:25
@cjcodes thanks. it works for me!
