### ISSUE TITLE
Noice Hides Status Bar

### ISSUE THREAD

**Issue by UnrealApex** [folke/noice.nvim#37] opened 2022-10-07 07:42 UTC
**Describe the bug**
For some odd reason Noice hides my statusbar.

**Which version of Neovim are you using?**
Gui(Neovide)
**Note**
The statusbar did appear in the TUI, but not in GUI clients(Neovide, Neovim-Qt).
**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>

10/4/2022 9:33:43 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: end_col value outside range

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_extmark'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\line\init.lua:55: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\block.lua:72: in function 'highlight'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:151: in function 'render'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:57: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:48>
	...
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>
	[C]: in function 'nvim_err_writeln'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\install.lua:169: in function 'cb'
	vim/_editor.lua:262: in function <vim/_editor.lua:261>

10/4/2022 9:53:47 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: end_col value outside range

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_extmark'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\line\init.lua:55: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\block.lua:72: in function 'highlight'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:151: in function 'render'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:57: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:48>
	...
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\hacks.lua:200: in function 'push'
	C:\Users\Aaron\.vim\plugged\nvim-notify/lua\notify\init.lua:214: in function 'notify'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:102: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:74>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

10/4/2022 9:53:52 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: end_col value outside range

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_extmark'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\line\init.lua:55: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\block.lua:72: in function 'highlight'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:151: in function 'render'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:57: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:48>
	...
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\hacks.lua:200: in function 'push'
	C:\Users\Aaron\.vim\plugged\nvim-notify/lua\notify\init.lua:214: in function 'notify'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:102: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:74>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

10/4/2022 9:57:08 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: end_col value outside range

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_extmark'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\line\init.lua:55: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\block.lua:72: in function 'highlight'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:151: in function 'render'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:57: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:48>
	...
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\hacks.lua:195: in function 'push'
	C:\Users\Aaron\.vim\plugged\nvim-notify/lua\notify\init.lua:214: in function 'notify'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:102: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:74>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

10/4/2022 10:49:06 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: Vim(append):Error executing lua callback: ...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:151: Keyboard interrupt
stack traceback:
	[C]: in function 'nvim_buf_set_option'
	...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:151: in function 'enable_syntax'
	...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:175: in function 'detach'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:490: in function 'detach_module'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:499: in function 'reattach_module'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:108: in function <...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:107>
	[C]: in function 'nvim_buf_set_option'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: in function 'set_buf_options'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:142: in function 'render'
	...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:137: in function <...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:126>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_option'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: in function 'set_buf_options'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:142: in function 'render'
	...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:137: in function <...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:126>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

10/4/2022 10:50:17 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: Vim(append):Error executing lua callback: ...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:151: Keyboard interrupt
stack traceback:
	[C]: in function 'nvim_buf_set_option'
	...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:151: in function 'enable_syntax'
	...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:169: in function 'attach'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:477: in function 'attach_module'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:500: in function 'reattach_module'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:108: in function <...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:107>
	[C]: in function 'nvim_buf_set_option'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: in function 'set_buf_options'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:142: in function 'render'
	...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:137: in function <...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:126>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_option'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: in function 'set_buf_options'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:142: in function 'render'
	...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:137: in function <...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:126>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

10/4/2022 10:53:21 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: end_col value outside range

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:101>
	[C]: in function 'nvim_buf_set_extmark'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\line\init.lua:55: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\block.lua:72: in function 'highlight'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:151: in function 'render'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:57: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:48>
	...
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\hacks.lua:195: in function 'push'
	C:\Users\Aaron\.vim\plugged\nvim-notify/lua\notify\init.lua:214: in function 'notify'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:102: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:74>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:107: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:107: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

10/6/2022 6:28:42 PM
...m\plugged\nvim-notify/lua/notify/service/buffer/init.lua:98: Vim(set):E218: autocommand nesting too deep

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/util/call.lua:102: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_set_option'
	...m\plugged\nvim-notify/lua/notify/service/buffer/init.lua:98: in function 'render'
	...ron\.vim\plugged\nvim-notify/lua/notify/service/init.lua:53: in function 'push'
	...s\Aaron\.vim\plugged\noice.nvim/lua/noice/util/hacks.lua:196: in function 'push'
	C:\Users\Aaron\.vim\plugged\nvim-notify/lua/notify/init.lua:214: in function 'notify'
	...\Aaron\.vim\plugged\noice.nvim/lua/noice/view/notify.lua:125: in function '_notify'
	...
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/util/call.lua:107: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/util/call.lua:92>
	...ers\Aaron\.vim\plugged\noice.nvim/lua/noice/view/nui.lua:126: in function 'hide'
	...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/view/init.lua:88: in function 'display'
	...ron\.vim\plugged\noice.nvim/lua/noice/message/router.lua:91: in function <...ron\.vim\plugged\noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...ron\.vim\plugged\noice.nvim/lua/noice/message/router.lua:34: in function 'fn'
	vim/_editor.lua:467: in function 'cb'
	vim/_editor.lua:262: in function <vim/_editor.lua:261>

10/6/2022 6:28:42 PM
...m\plugged\nvim-notify/lua/notify/service/buffer/init.lua:98: Vim(set):E218: autocommand nesting too deep

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/util/call.lua:102: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_set_option'
	...m\plugged\nvim-notify/lua/notify/service/buffer/init.lua:98: in function 'render'
	...ron\.vim\plugged\nvim-notify/lua/notify/service/init.lua:53: in function 'push'
	...s\Aaron\.vim\plugged\noice.nvim/lua/noice/util/hacks.lua:196: in function 'push'
	C:\Users\Aaron\.vim\plugged\nvim-notify/lua/notify/init.lua:214: in function 'notify'
	...\Aaron\.vim\plugged\noice.nvim/lua/noice/view/notify.lua:125: in function '_notify'
	...
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/util/call.lua:107: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/util/call.lua:92>
	...ers\Aaron\.vim\plugged\noice.nvim/lua/noice/view/nui.lua:126: in function 'hide'
	...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/view/init.lua:88: in function 'display'
	...ron\.vim\plugged\noice.nvim/lua/noice/message/router.lua:91: in function <...ron\.vim\plugged\noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...ron\.vim\plugged\noice.nvim/lua/noice/message/router.lua:34: in function 'fn'
	vim/_editor.lua:467: in function 'cb'
	vim/_editor.lua:262: in function <vim/_editor.lua:261>

</pre>
</details>

**Comment by Teyras** [comment] 2022-10-07 07:43
I also observed this with lualine in TUI.

**Comment by Allaman** [comment] 2022-10-07 11:47
Don't know if related but we also noticed issues with the status bar getting behind the last line (https://github.com/Allaman/nvim/issues/22). Confirmed with mini statusline and lualine

**Comment by folke** [comment] 2022-10-09 07:37
Closing this as a duplicate of https://github.com/folke/noice.nvim/issues/17

**Closed by folke** 2022-10-09 07:37 UTC
