### ISSUE TITLE
Multiple notifications for `E486: Pattern not found`

### ISSUE THREAD

**Issue by pBorak** [folke/noice.nvim#24] opened 2022-10-05 14:29 UTC
**Describe the bug**
When searching fails there are multiple notification popups.

**What version of Nevoim are you using?**
```
❯ nvim --version
NVIM v0.8.0
Build type: Release
```

**To Reproduce**
Search for the pattern that is not present

**Expected behavior**

There should be one notification for E486 and presumably, one for `Search hit Bottom` ?

**Screenshots**

<img width="1512" alt="Screenshot 2022-10-05 at 16 25 51" src="https://user-images.githubusercontent.com/45797239/194085404-9f78c1b9-a1dc-4c16-b7af-ab424c49c397.png">

**Noice log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
Wed Oct  5 16:28:32 2022
...art/nvim-notify/lua/notify/service/buffer/highlights.lua:40: Invalid highlight name: NotifyERRORTitle27720

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_set_hl'
	...art/nvim-notify/lua/notify/service/buffer/highlights.lua:40: in function 'linked_group'
	...art/nvim-notify/lua/notify/service/buffer/highlights.lua:45: in function 'NotifyBufHighlights'
	...ker/start/nvim-notify/lua/notify/service/buffer/init.lua:43: in function '_create_highlights'
	...ker/start/nvim-notify/lua/notify/service/buffer/init.lua:38: in function 'set_notification'
	...ker/start/nvim-notify/lua/notify/service/buffer/init.lua:32: in function 'NotificationBuf'
	...
	...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:214: in function 'notify'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:125: in function '_notify'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:151: in function <...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:128>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	...vim/site/pack/packer/opt/noice.nvim/lua/noice/router.lua:91: in function <...vim/site/pack/packer/opt/noice.nvim/lua/noice/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>
</pre>
</details>

**Comment by gennaro-tedesco** [comment] 2022-10-05 15:37
I am observing that a similar one happens in correspondence of "No write since last changes" (see screenshot):

![Screenshot 2022-10-05 at 17 33 12](https://user-images.githubusercontent.com/15387611/194102063-470ed076-76b4-452c-9432-c45c15107080.png)

I have noticed it shortly ago only, not sure if it is intended behaviour or the consequence of one of the latest commits (I mention it here in case it may be useful to debug the original issue as additional information).

**Comment by folke** [comment] 2022-10-05 20:51
@pBorak I had the same earlier today and on longer see this happen, so I likely fixed it :)

Can you let me know if you still have it?

**Comment by folke** [comment] 2022-10-05 20:52
@gennaro-tedesco was probably the same. Does it still happen with the latest version?

**Comment by gennaro-tedesco** [comment] 2022-10-05 23:38
I have updated the plug-in but I still observe the same behaviour: see video below to showcase what occurs


https://user-images.githubusercontent.com/15387611/194182692-9092831b-8b86-4737-a7be-3ad343b56f85.mov

**Comment by Shougo** [comment] 2022-10-06 02:33
Please see this.

It is from `nvim --clean`.

![スクリーンショット_2022-10-06_11-32-28](https://user-images.githubusercontent.com/41495/194201179-faf4ad30-9b99-4784-962f-83c360e17671.png)

Two error messages are generated.  It is not bug.

**Comment by gennaro-tedesco** [comment] 2022-10-06 07:19
@Shougo you are precisely right, I guess I had just never noticed. Apologies for the noise!

**Comment by Shougo** [comment] 2022-10-06 07:34
So it should be closed?

**Comment by pBorak** [comment] 2022-10-06 07:36
Just not yet, I have updated the plugin but still see the same issue.

**Comment by Shougo** [comment] 2022-10-06 07:38
Please upload the reproduce instruction.
I will test it.

**Comment by pBorak** [comment] 2022-10-06 07:58
@folke 
Okay I found the thing that messes this up
If you set `vim.opt.lazyredraw` to true the issue still occurs.

**Comment by folke** [comment] 2022-10-06 09:55
@pBorak you really shouldn't set lazyredraw. That's not an option meant to be set. Only temporarily inside scripts.

![image](https://user-images.githubusercontent.com/292349/194283797-6734f5ce-3348-45de-97ed-885ca96b8312.png)

**Comment by folke** [comment] 2022-10-06 09:56
Closing this, since Noice simply won't work correctly when lazyredraw is set

**Comment by pBorak** [comment] 2022-10-06 09:56
Thanks for handling it!

**Closed by folke** 2022-10-06 09:56 UTC

**Comment by Shougo** [comment] 2022-10-06 10:45
I think `noice.nvim` should check `lazyredraw` option is set and warn.

Because another people have the problem with it.

**Comment by Meow-2** [comment] 2022-10-26 14:53
> 

how to disable this warning? I don't set lazyredraw, but my plugin(vim-visual-multi) may set lazyredraw when I use it and I will see this warning.

**Comment by folke** [comment] 2022-10-26 15:14
@Meow-2 they should only set it temporarily, not forever.

**Comment by folke** [comment] 2022-10-26 15:15
Or they probbly do disable it afterwards?

**Comment by Meow-2** [comment] 2022-10-26 15:35
> Or they probbly do disable it afterwards?

Yes, vim-visual-multi only set it temporarily, how can I hide this warning?

**Comment by folke** [comment] 2022-10-26 15:40
I jsut added an option. `config.health.checker` disables the health checker after setup

**Comment by Meow-2** [comment] 2022-10-26 15:47
> I jsut added an option. `config.health.checker` disables the health checker after setup

It works, thank you!

**Comment by smjonas** [comment] 2022-10-29 11:00
I am also setting `vim.o.lazyredraw` temporarily inside the preview callback function of my plugin `live-command.nvim`: https://github.com/smjonas/live-command.nvim/blob/ce4b104ce702c7bb9fdff863059af6d47107ca61/lua/live-command/init.lua#L200 

I am not sure why this error is shown because it's reset after running the command. I don't want to disable this error globally so would it be possible to detect that this option was only set temporarily and not show an error message in that case?

**Comment by folke** [comment] 2022-10-29 11:07
@smjonas just made a change that checks for `lazyredraw` during startup only

**Comment by smjonas** [comment] 2022-10-29 11:14
Thank you, while that is an improvement, the warning is still shown when previewing the command for the first time, e.g. when typing `:Norm A`.

**Comment by folke** [comment] 2022-10-29 11:18
@smjonas it really shouldn't. Lazyredraw is now only checked during noice startup. So after that even if it is set, we no longer show a warning.

Maybe something else is setting lazyredraw? `:verbose set lazyredraw?`

**Comment by smjonas** [comment] 2022-10-29 11:31
What I have observed is running `:set lazyredraw` manually after noice has already started (i.e. some messages were displayed), it will still cause the warning to be shown.

**Comment by folke** [comment] 2022-10-29 11:46
@smjonas you're right, sorry. Fixed!

**Comment by smjonas** [comment] 2022-10-29 11:50
Thank you, can confirm it's fixed now!
