### ISSUE TITLE
`:Noice` doesn't populate unless you run `:history` first

### ISSUE THREAD

**Issue by mrjones2014** [folke/noice.nvim#14] opened 2022-10-04 10:48 UTC
**Describe the bug**
Run `:Noice`. Close the opened buffer. Run it again. No buffer is opened and you get an error.

**To Reproduce**
See above.

**Expected behavior**
Running `:Noice` the second time re-opens the buffer like the first time.

**Screenshots**
![image](https://user-images.githubusercontent.com/8648891/193800650-4f38fed8-e441-4f0d-bb11-43ac4ff4e280.png)

**Noice log**
```


Tue Oct  4 06:46:16 2022
.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:140: Expected Lua number

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:54: in function 'on_error'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:97: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:96>
	[C]: in function 'nvim_buf_set_lines'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:140: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:160: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:153>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:77: in function 'display'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/commands.lua:34: in function 'history'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/commands.lua:47: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/commands.lua:42>

Tue Oct  4 06:46:37 2022
.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:140: Expected Lua number

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:54: in function 'on_error'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:97: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:96>
	[C]: in function 'nvim_buf_set_lines'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:140: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:160: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:153>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:77: in function 'display'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/commands.lua:34: in function 'history'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/commands.lua:47: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/commands.lua:42>

Tue Oct  4 06:48:12 2022
.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:140: Expected Lua number

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:54: in function 'on_error'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:97: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:96>
	[C]: in function 'nvim_buf_set_lines'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:140: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:160: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:153>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:77: in function 'display'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/commands.lua:34: in function 'history'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/commands.lua:47: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/commands.lua:42>
```

**Comment by mrjones2014** [comment] 2022-10-04 11:55
Ah, it probably has to do with this. If you run `:Noice`, it doesn't actually populate until you run `:history` first. I'll update the issue title.

**Comment by folke** [comment] 2022-10-04 13:16
This has nothing to do with the `:history` command :)

I can't reproduce this, so can you try with the latest version and report back with the logs?

**Comment by mrjones2014** [comment] 2022-10-04 13:32
I'm still able to reproduce, maybe I'm using it wrong?

I'm opening Neovim, running `:Noice` and it opens an empty buffer in a new window. I close the window with `:q`. Then if I run `:Noice` again, I get the error.

If I then run something which prints messages (such as `:history` for example, I guess that's why I was confused and thought it was related), `:Noice` then works properly.

**Comment by Shougo** [comment] 2022-10-04 13:36
@mrjones2014 You should create minimal init.vim for it.

**Comment by folke** [comment] 2022-10-04 13:37
I could reproduce it with `:q`. Before I closed it with `q`, which did not trigger the issue.

Should be fixed now.

**Closed** 2022-10-04 13:37 UTC
