### ISSUE TITLE
bug: slow even with minimal repro

### ISSUE THREAD

**Issue by WillEhrendreich** [folke/noice.nvim#498] opened 2023-06-06 17:54 UTC
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-422+g68e2d7229

### Operating system/version

Windows 10

### Describe the bug

this is the only place I could find someone else having a problem..

https://github.com/folke/noice.nvim/discussions/311

I'm fighting the slowdown too, and it's absolutely in the 500ms range. 

I'm on windows 10, and I've tried a couple of things. 

I've done the checkhealth, it's all OK.

If i take the minimal repro code from below, and use that only as a config, it's still a LITTLE bit laggy at first, but then I go into any file, and it starts chugging terribly again. 

I have to specifically disable cmdline and messages in the options to be able to have a smooth experience with anything more than that. 

### Steps To Reproduce

start with the minimal repro,
open up any file,
try to type anything, it will have almost half a second of lag between each keypress. 

### Expected Behavior

smooth like buttah. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment] 2023-06-06 17:58
As I mentioned before, I can't reproduce this and your indeed only the second person mentioning this. Are you using an up to date Neovim version?

Noice should have 0 input lag.

Closing this, since the repro does not reproduce it.

**Closed by folke** 2023-06-06 17:58 UTC
Labels: bug

**Comment by WillEhrendreich** [comment] 2023-06-06 18:03
I'm using NVIM v0.10.0-dev-422+g68e2d7229.

it only starts to lag after i open a file, so it has something to do with what happens when cmdline is being rendered with files open.

have you tried reproducing it on a windows machine, or are you on linux?

**Comment by folke** [comment] 2023-06-06 18:05
Yep, works fine on windows for me as well

**Comment by WillEhrendreich** [comment] 2023-06-06 18:10
ok, well that's good at least.. 
 
If you were me, what would you do in the situation? 

How would you go about profiling this or finding where the issue lies?

**Comment by folke** [comment] 2023-06-06 18:12
Can you check `:Noice log`?

I actually just checked mine and I do see there's an issue somewhere. Will check if that's possibly related somehow,

**Comment by folke** [comment] 2023-06-06 18:13
nevermind, that was me testing earlier today. Your log might still be useful though

**Comment by WillEhrendreich** [comment] 2023-06-06 18:31
the trouble is it isn't showing any errors for when the slowdown is happening. 

can I get it to log more? set it to trace level?

**Comment by folke** [comment] 2023-06-06 18:33
You're sure you have this with just the repro?
Make sure to update plugins after running the repro, or delete the `./.repro` folder first.

**Comment by WillEhrendreich** [comment] 2023-06-06 18:46
![noiceMinimalConfigLag](https://github.com/folke/noice.nvim/assets/55286472/e912d739-798e-4fff-8da9-458f206499bb)

-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)



-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
{
  "folke/noice.nvim",
  event = "VeryLazy",
  opts = {
    -- add any options here
  },
  dependencies = {
    -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
    "MunifTanjim/nui.nvim",
    -- OPTIONAL:
    --   `nvim-notify` is only needed, if you want to use the notification view.
    --   If not available, we use `mini` as the fallback
    "rcarriga/nvim-notify",
    }
}
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
 
require("noice").setup({
 lsp = {
    -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
    override = {
      ["vim.lsp.util.convert_input_to_markdown_lines"] = false,
      ["vim.lsp.util.stylize_markdown"] = false,
      ["cmp.entry.get_documentation"] = false,
    },
  },
  -- you can enable a preset for easier configuration
  presets = {
    bottom_search = false, -- use a classic bottom cmdline for search
    command_palette = false, -- position the cmdline and popupmenu together
    long_message_to_split = false, -- long messages will be sent to a split
    inc_rename = false, -- enables an input dialog for inc-rename.nvim
    lsp_doc_border = false, -- add a border to hover docs and signature help
  },

})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

**Comment by WillEhrendreich** [comment] 2023-06-06 19:07
can I somehow attach a profiler to this? how would I do that?
