### ISSUE TITLE
bug: never ending error messages when gopls shows an error in floating window 

### ISSUE THREAD

**Issue by arsham** [folke/noice.nvim#193] opened 2022-11-03 13:46 UTC
**Describe the bug**
I have a plugin that put some tmp go files in `/tmp` folder and gopls is not happy about it and it shows a floating window like this:
![3](https://user-images.githubusercontent.com/428611/199733491-41466d1c-d0a1-4d43-b8cb-240a06e8e0e8.png)

If I remove the floating window with this block of code:
```lua
  for _, win in ipairs(vim.api.nvim_list_wins()) do
    local config = vim.api.nvim_win_get_config(win)
    if config.relative ~= "" then
      vim.api.nvim_win_close(win, false)
    end
  end
```

Soon after I get a flood of never ending errors:
<details>
    <summary>Click to view screenshot</summary>

![2](https://user-images.githubusercontent.com/428611/199733597-6647b4d7-50ec-4db1-8b84-4cd8b3f52169.png)

</details>

The same happens if I remove any notifications created by this plugin:
```
stack traceback:
        [C]: in function 'nvim_win_set_config'
        ...m/site/pack/packer/opt/nui.nvim/lua/nui/popup/border.lua:541: in function '_relayout'
        ...vim/site/pack/packer/opt/nui.nvim/lua/nui/popup/init.lua:359: in function 'update_layout'
        ...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:248: in function 'update_layout'
        ...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:175: in function 'reset'
        .../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:98: in function 'check_options'
        .../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:121: in function 'display'
        ...ck/packer/opt/noice.nvim/lua/noice/view/backend/mini.lua:88: in function 'update'
        ...ck/packer/opt/noice.nvim/lua/noice/view/backend/mini.lua:58: in function <...ck/packer/opt/noice.nvim/lua/noice/view/backend/mini.lua:57>
```
<details>
<summary>Screenshot</summary>

![1](https://user-images.githubusercontent.com/428611/199733838-a8a4b6d3-334d-4346-8c7a-19bd47c41729.png)

</details>

**Which version of Neovim are you using?**
```
NVIM v0.9.0-dev-213+gcc5b7368d6-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```
In Alacritty.

**To Reproduce**
1. Create a valid go file `/tmp/main.go`
2. CD into /tmp
3. Open file.
4. Use the snippet above to remove the floating window.

And:
1. Do something that shows a message with `mini` backend
2. While the notification is still visible, invoke the snippet mentioned above.

**Expected Behavior**
To continue without error. The floating window doesn't exists any more, but looks that the plugin tries to reach it.

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
```
Thu 03 Nov 2022 13:36:32 GMT
.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:195: Invalid window id: 1003

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:140: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:139>
	[C]: in function 'nvim_win_set_option'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:195: in function 'set_win_options'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:269: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:251>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
	...
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:123: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:115: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:74>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:130>
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/init.lua:104: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

Thu 03 Nov 2022 13:36:32 GMT
.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:195: Invalid window id: 1003

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:140: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:139>
	[C]: in function 'nvim_win_set_option'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:195: in function 'set_win_options'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:269: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:251>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
	...
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:123: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:115: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:74>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:130>
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/init.lua:104: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

```

Goes on an on.
</pre>
</details>

Please let me know if you need more information.
Thank you.

**Comment by cenk1cenk2** [comment] 2022-11-04 13:44
I suppose it is also somewhat similar to this https://github.com/folke/noice.nvim/issues/175.

**Comment by folke** [comment] 2022-11-07 10:31
You're closing windows managed by a plugin. What do you expect to happen?
You can't just randomly delete windows/buffers and not expect any errors to happen.

Closing this.

Either way, I'll look into #175, since that's the real issue I guess

**Closed by folke** 2022-11-07 10:31 UTC
Labels: bug

**Comment by folke** [comment] 2022-11-07 10:41
I can't reproduce this. Opening a go file in tmp, does not give an error.
