### ISSUE TITLE
Not compatible with neovide

### ISSUE THREAD

**Issue by nick4tech** [folke/noice.nvim#17] opened 2022-10-04 22:22 UTC
**Describe the bug**
I've installed the plugin with packer. Used one of the config recipes from the wiki but I can't get it to work.

**To Reproduce**
Install with Packer
Copy the config recipe from the wiki:
```lua
  use {
    'folke/noice.nvim',
    event = "VimEnter",
    requires = {
      -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
      "MunifTanjim/nui.nvim",
      "rcarriga/nvim-notify",
      "hrsh7th/nvim-cmp",
    },
    config = function()
      require("noice").setup({
        views = {
          cmdline_popup = {
            border = {
              style = "none",
              padding = { 2, 3 },
            },
            filter_options = {},
            win_options = {
              winhighlight = "NormalFloat:NormalFloat,FloatBorder:FloatBorder",
            },
          },
        },
        routes = {
          {
            filter = {
              event = "cmdline",
              find = "^%s*[/?]",
            },
            view = "cmdline",
          },
        },
      })
    end
  }
```
I also tried without lazy loading and still didn't work. Also tried running `Noice enable`, didn't work.

**Expected behavior**
I'd expect the command line to appear in a popup on the center of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/6836442/193940730-73048e46-385e-4aad-b264-7cb1e8e7c46f.png)

This is how my command line looks.

**Noice log**
Noice log is empty.
Here are the stats:
![image](https://user-images.githubusercontent.com/6836442/193940881-22cfb8a3-482a-4750-8b17-f5930b3b4b7b.png)

**Comment by folke** [comment] 2022-10-04 22:52
In the route, you specify it needs to go to the `cmdline`. If you want the popup, change this to `cmdline_popup`.
You also wont have syntax highlighting, since you removed the opts with filtetype vim.

Just remove the routes in your config.

**Comment by folke** [comment] 2022-10-04 22:53
Nevermind, that's for the search cmdline

**Comment by folke** [comment] 2022-10-04 22:55
Just tried your config and it works for me.
Are you using Neoivm 0.8.0? Do you use a gui?

**Comment by nick4tech** [comment] 2022-10-04 23:02
So I removed all the configs and just stuck to the default. I think I know what's happening. It seems to be incompatible with `neovide`, which the gui I use. I tried running it from `nvim` in terminal and it worked.

**Comment by Shougo** [comment] 2022-10-05 01:56
Please see this.

https://github.com/folke/noice.nvim/issues/10

**Comment by folke** [comment] 2022-10-05 05:19
For me the popup etc does work in the latest Neovide version, but there's another issue with `:messages` that crashes Neovide.

I'll keep this open for now and will add it to the tracking issue

**Comment by clason** [comment] 2022-10-24 16:23
Is this with our without `--multigrid`?

**Comment by alerque** [comment] 2022-10-24 17:38
I run Neovide with `--multigrid` and am not able to use noice with it.

**Comment by folke** [comment] 2022-10-24 17:38
So I just tested again with the latest version of Neovide, Neovim & Noice, and everything seems to be working now :)

I pushed a change, so that Noice still shows a warning of running inside Neovide, but it will start.

Would be great if others can test as well to see that everything is working inside Neovide now.

@clason with `--multigrid`, something is broken. No errors, but Noice can't seem to override the cmdline.

**Comment by folke** [comment] 2022-10-24 17:38
@alerque try without multigrid. It seems to work fine for me

**Comment by clason** [comment] 2022-10-24 17:40
> @clason with --multigrid

That would be my expectation as well; `multigrid` has a number of issues with newer TUI functionality.

**Comment by alerque** [comment] 2022-10-24 17:41
@folke What's the point? When I want to forego smooth scrolling to get noice features I just run NeoVIM in a terminal.

**Comment by clason** [comment] 2022-10-24 17:42
Smooth scrolling has nothing to do with `multigrid`...

**Comment by folke** [comment] 2022-10-24 17:44
@alerque the point was to test and see if that works for you as well, so we can narrow down the issue to `--multigrid`

**Comment by clason** [comment] 2022-10-24 17:54
In any case, can I suggest turning the hard error into a warning, even with `multigrid`? A lot of features still work fine.

**Comment by folke** [comment] 2022-10-24 18:01
@clason did that already  :)

**Comment by james2doyle** [comment] 2022-10-24 18:34
Just tested with the latest build of Neovide (not using `multigrid`) from the main branch with the latest changes on noice and it seems to work:

![Screen Shot 2022-10-24 at 11 27 32 AM](https://user-images.githubusercontent.com/1425304/197599959-176fd3d3-f401-4746-8dd6-400f4b5e5bce.png)
![Screen Shot 2022-10-24 at 11 29 00 AM](https://user-images.githubusercontent.com/1425304/197599962-ebf7b9c1-24a3-4e6a-9e86-28d782ef7aac.png)

**Comment by folke** [comment] 2022-10-24 18:46
@james2doyle that doens't seem right. Thats the call to `vim.treesitter`.

It seems like your installation (runtime directory) is messed up.

**Comment by james2doyle** [comment] 2022-10-24 18:56
Ah ok. I will look into that. I used to build from source before 0.8 was out so I am sure it is a holdover from the mess I made

**Comment by clason** [comment] 2022-10-24 19:07
Very likely then. Clean out your runtime directory and install again.

**Comment by james2doyle** [comment] 2022-10-24 19:22
Got it. I had a custom set ENV VAR for it and once it was removed it worked perfectly

**Comment by UnrealApex** [comment] 2022-10-25 02:27
Neovide crashes when using keymaps with multiple Ex-commands. Here is a minimal reproducible example that works:
```
nnoremap <C-l> :echo<CR>:echo<CR>:echo<CR>
```

**Comment by khalidchawtany** [comment] 2022-10-25 02:53
@UnrealApex the same happens in neovim-qt. However, its neovim’s bug, as no plugin should be able to make it crash https://github.com/folke/noice.nvim/issues/106

**Comment by UnrealApex** [comment] 2022-10-25 05:22
Unfortunately certain errors *do* make Neovide crash. Hence why this issue was opened.

**Comment by folke** [comment] 2022-10-25 05:35
@UnrealApex @khalidchawtany is right, there's little I can do to prevent those crashes. Either a bug on the Neovim or Neovide side.

I keep this issue open to track what works and what doesn't. It's not possible for me to fix any of these issues.

**Comment by folke** [comment] 2022-10-25 05:37
The specific issue @khalidchawtany was refering to, is fixed on the latest Neovim nightly.

If you want to help testing Neovide, make sure to only report issues here that happen on nightly. We know there's a bunch of issues with Neovide, Noice and Neovim stable.

**Comment by folke** [comment] 2022-10-25 16:40
@sid-6581 that's the errors I used to get, but they're gone for me now

**Comment by UnrealApex** [comment] 2022-10-26 02:36
> @UnrealApex @khalidchawtany is right, there's little I can do to prevent those crashes. Either a bug on the Neovim or Neovide side.

Keymaps with multiple commands work fine in nightly(TUI).

**Comment by folke** [comment] 2022-11-16 20:45
fyi: I was able to work around an issue where Neovide would crash almost immediately, event without multigrid.

**Comment by folke** [comment] 2022-11-16 23:30
Can you check if it works in TUI?

The error you're seeing is because of missing symbols in the Neovim that Neovide uses.

It shouldn't trigger issues in TUI.

**Comment by sid-6581** [comment] 2022-11-16 23:34
Sorry, I forgot to mention that it's also a problem in TUI on Windows. It behaves exactly the same, so it's not just a GUI issue. TUI on Linux (in WSL2) doesn't have this issue.

In WSL I'm running neovim nightly installed through homebrew, which is currently `NVIM v0.9.0-dev-1537+gc404f9b4b-dirty`.

In Windows I'm running neovim nightly installed through scoop, which is currently `NVIM v0.9.0-dev-326+gfa7e1e260`.

I'm not sure if that makes a difference. I update everything every day, and everything was working yesterday. (Except neovide was probably crashing, but I wouldn't have noticed because I switched to neovim-qt so I could use noice.)

**Comment by sid-6581** [comment] 2022-11-17 14:08
Just wanted to follow up and say that it looks like the latest commit fixed the issue! No crashes and no warnings on Windows/Neovide so far. Thanks a lot, your hard work with all your plugins is extremely appreciated.

**Comment by jinzhongjia** [comment] 2022-11-18 12:15
em... now,on archlinux, it still crash, but I can see the cmdline before crashing
Now, I use the neovim(nightly version),and neovide is 0.10.3

**Comment by folke** [comment] 2022-11-18 12:32
it doesn't crash for me on Fedora.
Are you sure you're using the latest version?

**Comment by alerque** [comment] 2022-11-18 12:32
I think you'd need the Neovide VCS package and compile the HEAD version for this to work.

**Comment by jinzhongjia** [comment] 2022-11-18 12:55
@alerque @folke 
I try compile neovide(branch is main) on my archlinux, and compile successfully, launch it well, but when I get the `cmdline`, it crashes and the console print these:
```
ERROR [neovide::error_handling] Could not parse event from neovim: invalid array format 0
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid array format 0', src/error_handling.rs:5:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR [neovide::bridge] Error joining IO loop: 'task 13 panicked'

```

**Comment by jinzhongjia** [comment] 2022-11-18 12:56
> @alerque @folke I try compile neovide(branch is main) on my archlinux, and compile successfully, launch it well, but when I get the `cmdline`, it crashes and the console print these:
> 
> ```
> ERROR [neovide::error_handling] Could not parse event from neovim: invalid array format 0
> thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid array format 0', src/error_handling.rs:5:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ERROR [neovide::bridge] Error joining IO loop: 'task 13 panicked'
> ```

I didn't know why it will crash.

**Comment by jinzhongjia** [comment] 2022-11-18 13:02
> @alerque @folke I try compile neovide(branch is main) on my archlinux, and compile successfully, launch it well, but when I get the `cmdline`, it crashes and the console print these:
> 
> ```
> ERROR [neovide::error_handling] Could not parse event from neovim: invalid array format 0
> thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid array format 0', src/error_handling.rs:5:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ERROR [neovide::bridge] Error joining IO loop: 'task 13 panicked'
> ```

and my noice's config is default

**Comment by jinzhongjia** [comment] 2022-11-18 13:06
It is very strange, I found that when I called up the cmdline on the dashboard, it would crash, but it would not crash on other pages
so that means the plugin `dashboard.nvim` cause crashing?

**Comment by jinzhongjia** [comment] 2022-11-18 14:28
Now, I have replaced `dashboard.nvim` to `alpha.nvim`

**Comment by luiz00martins** [comment] 2022-12-18 14:16
> fyi: I was able to work around an issue where Neovide would crash almost immediately, event without multigrid.

I think I'm getting this error on Windows. Open up Neovide, type `:`, and it crashes.

**Comment by Icy-Thought** [comment] 2022-12-23 15:45
Managed to reduce the experienced failure to Neovide's `--multigrid` option (already mentioned by others) + `dashboard.nvim` when used without `--multigrid`. (similar to @jinzhongjia experience)

**Relevant info**:
- Neovim version: `NVIM v0.9.0-dev` (Nix overlay)

**Comment by shaunsingh** [comment] 2023-02-03 02:21
Is there something we can do on the neovide end to improve the multigrain experience? From what I understand, noice is taking advantage of `ext_cmdline`, which `neovide --multigrid` handles.

> dashboard.nvim
Is the issue reproducable without noice? in which case please open a ticket in the neovide repo. My guess is that neovide like to crash on `os.execute` due to another upstream issue and dashboard.nvim like to call it, somewhere

**Comment by Ciel-MC** [comment] 2023-02-12 09:39
Tried it today, Neovide 0.10.3-1 with multigrid disabled seems to function fine so far. (Linux)

**Comment by ryo33** [comment] 2023-02-18 15:28
https://github.com/ryo33/neovide/commit/1c0ef4dc1d1d2f7c319c62247569277cea9f0dd1 This patch should help to investigate this issue (Tell me if anybody knows a better way to debug-print the event that causes a crash.

**Comment by ryo33** [comment] 2023-02-20 14:59
I've opened https://github.com/neovim/neovim/issues/22344 for this.

**Comment by xbladesub** [comment] 2023-02-26 04:52
How to disable this notification?
<img width="471" alt="image" src="https://user-images.githubusercontent.com/45129790/221392999-99552e89-c6f4-45ae-9be2-e107662ba0dd.png">

**Comment by xbladesub** [comment] 2023-02-26 08:17
For me everything is ok so far... I don't know guys how you can use `--multigrid` with neovim 0.8+. Hope this bug will be fixed soon. I love Neovide's smooth scroll + smooth text input. No any other plugin can do this.

**Comment by xbladesub** [comment] 2023-02-26 09:03
Ok, it crahes for me if I do `ciB` for example. Strange...

**Comment by Ciel-MC** [comment] 2023-02-26 09:05
> How to disable this notification? <img alt="image" width="471" src="https://user-images.githubusercontent.com/45129790/221392999-99552e89-c6f4-45ae-9be2-e107662ba0dd.png">

You can't, it's something to keep in mind

> Ok, it crahes for me if I do `ciB` for example. Strange...

Yeah, we have discovered that neovide crashes if multiple lines were deleted and the resulting buffer isn't empty, see neovide's issue on this for more info.

**Comment by xbladesub** [comment] 2023-02-26 09:08
> > How to disable this notification? <img alt="image" width="471" src="https://user-images.githubusercontent.com/45129790/221392999-99552e89-c6f4-45ae-9be2-e107662ba0dd.png">
> 
> You can't, it's something to keep in mind
> 
> > Ok, it crahes for me if I do `ciB` for example. Strange...
> 
> Yeah, we have discovered that neovide crashes if multiple lines were deleted and the resulting buffer isn't empty, see neovide's issue on this for more info.

Is it possible to fix with noice settings? I mean deletion bug

**Comment by folke** [comment] 2023-02-27 09:09
@xbladesub first of all, you should be running Neovim Nightly, to minimize any segfaults. 

That notification window you see is nvim-notify. Just disable it if you don't want that

**Comment by xbladesub** [comment] 2023-02-27 14:03
> @xbladesub first of all, you should be running Neovim Nightly, to minimize any segfaults.
> 
> That notification window you see is nvim-notify. Just disable it if you don't want that

I have tree-sitter issues with rust buffers on nightly neovim. I just disabled everything except cmdline and it's ok, can work. But still crashes sometimes while starting to search with `/` ))

**Comment by 1538379200** [comment] 2023-02-28 02:04
Maybe it was ```dashboard``` that crashed ```noice```, not neovide.
![image](https://user-images.githubusercontent.com/42434762/221734064-f3493f75-c259-4e8c-a1aa-2efccba7b44a.png)

**Comment by xbladesub** [comment] 2023-03-24 04:34
any update on this guys?

**Comment by luisiacc** [comment] 2023-04-23 22:29
Gonna add this in here, maybe it's related, It has also been mentioned on this thread, same crash as with `ciB`:

[ci{ causes neovide to exit when using folke/noice plugin](https://github.com/neovide/neovide/issues/1847)

**Comment by ryo33** [comment] 2023-06-27 12:50
https://github.com/neovim/neovim/issues/22344#issuecomment-1556269831
Can we stop triggering redraw events within the lua callback as this comment? I know the redraw are inherently needed, but I imagine there are workarounds like deferring them (by queueing?) or something.

References:
https://github.com/neovide/neovide/issues/1751#issuecomment-1435915499
https://github.com/neovide/neovide/issues/1751#issuecomment-1436498838

**Comment by fredizzimo** [comment] 2023-07-16 21:12
It has been reported here for example https://github.com/neovide/neovide/issues/1737#issuecomment-1465069158 that disabling the messages stops the crashes. 

This is constantly causing headaches for Neovide users, since it's not clear for them what's causing the problem. @folke, would it be possible to disable that automatically with a warning or something, if Neovide is running? You can check with `if vim.g.neovide`. Of course that's just a temporary solution until the actual problem is fixed.

On the Neovide side, there's not much we can do, since the event we receive from Neovim is completely malformed.

**Comment by folke** [comment] 2023-07-17 07:46
@fredizzimo that's already the case.

This message is show for users running noice inside Neovide:
`Noice may not work correctly with Neovide. Please see #17`

fyi: I'm not sure what is diffrerent with other GUIs but for the others I tested, Noice does not seem to be causing issues. It's been a while since I tested in other GUIs though, so maybe some upstream Neovim issues might have been introduced in the meantime.

**Comment by folke** [comment] 2023-07-17 07:59
@ryo33 it's unfortunately not that simple. The big issue is that noice implements `ui_attach`, so noice has to be able to draw itself during/right before a blocking event. Otherwise there are a lot of cases where the cmdline would not be visible for example while it should. Using `vim.schedule` in those cases wouldn't work, since that would be delayed till whatever blocking event resolves.

**Closed** 2023-07-17 09:35 UTC
Labels: upstream

**Comment by folke** [comment] 2023-07-17 09:37
I'm pretty confident I was able to fix Noice with Neovide.

It should even work properly with `--multigrid` enabled now.

The fix turned out to be easy and straightforward.

Basically, Noice stops propagating events handled by Noice to other GUis that may be attached.

Would be great if others can confirm this no longer crashes Neovide.

**Comment by edjeffreys** [comment] 2023-07-17 09:43
>Would be great if others can confirm this no longer crashes Neovide

Can confirm Neovide no longer crashes 🎉  thanks for that fix @folke!

**Comment by wvffle** [comment] 2023-07-18 23:43
Works fine even for `--multigrid` but the blur isn't working for noice popups

**Comment by Ciel-MC** [comment] 2023-07-19 00:29
I just tried disabling Noice while using Neovide and uhhh, this happened after I opened and closed a monorepo.nvim window. I think it has something to do with nvim-cmp for the cmdline
<img width="696" alt="image" src="https://github.com/folke/noice.nvim/assets/47144701/0a57fb03-f128-46a4-b801-63aabb4ad811">
It doesn't seem to happen on regular nvim.

**Comment by folke** [comment] 2023-07-19 09:28
@Ciel-MC that doesn't have anything to do with Neovide I think.
What caused this error? How did you disable noice?

**Comment by Ciel-MC** [comment] 2023-07-19 10:43
> @Ciel-MC that doesn't have anything to do with Neovide I think.
> What caused this error? How did you disable noice?

I disablo it with :NoiceDisable

I'm not sure, I suspect it is due to cmp trying to trigger completion?

I think it's to do with Neovide because it doesn't happen when I use the terminal
