### ISSUE TITLE
Termianl tital bar is keep flashing with updated text

### ISSUE THREAD

**Issue by dhruvinsh** [folke/noice.nvim#182] opened 2022-10-30 17:48 UTC
**Describe the bug**
I am using linux mint with kitty terminal on fairly slow hardware (i5-8250u) and using Neovim (0.8.0). When neovim fired, LSP take about minute or so to load the diagnostics and workspace. It can be seen by the bottom right lsp progress bar.

I have another virtual machine (just 2 core but 4.4 GHz processor) takes about 1 sec to finish the LSP progress. So I do see the kitty termianl titlebar updates but its fairly quick compare to latptop.

While it is happening kitty terminal tital bar is keep updating text. Video is attached here, but please note that video is not justifying what I am seeing here. In actual scenarious kitty termianl's title bar is keep flashing new data and its about 10-20 updates per seconds.
[cinnamon-2022-10-30T132359-0400.webm](https://user-images.githubusercontent.com/33428164/198892575-85ec4571-2924-4132-9cc2-4d6de1c9c206.webm)

**Which version of Neovim are you using?**
Neovim 0.8.0
**To Reproduce**
Steps to reproduce the behavior (I believe its happens only on slow hardware):
1. Get a slow hardware (or trottle the lsp progress in some way)
2. fire up the LSP server
3. see the titlebar updated till done with LSP progress bar (loading workspace and diagnosing workspace)

**Expected Behavior**
keep the titlebar name to opened filename only not to noice messages `scrollbar (noice://<some number>)` from loading workspace or diagnosing workspace LSP progress.

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
It was empty!
</pre>
</details>

**Comment by sid-6581** [comment] 2022-10-31 00:53
I'm seeing the same thing on very powerful hardware. It also leaves the wrong title, and never restores the file name:

![image](https://user-images.githubusercontent.com/28602336/198911008-c9fe5096-80d7-4e50-9e4f-dd09b616692d.png)

**Comment by eli-pixil** [comment] 2022-11-02 18:08
Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Dhruvin Shah ***@***.***> Datum: 30.10.22  18:48  (GMT+01:00) An: "folke/noice.nvim" ***@***.***> Cc: Subscribed ***@***.***> Betreff: [folke/noice.nvim] Termianl tital bar is keep flashing with updated text (Issue #182) 
Describe the bug
I am using linux mint with kitty terminal on fairly slow hardware (i5-8250u) and using Neovim (0.8.0). When neovim fired, LSP take about minute or so to load the diagnostics and workspace. It can be seen by the bottom right lsp progress bar.
I have another virtual machine (just 2 core but 4.4 GHz processor) takes about 1 sec to finish the LSP progress. So I do see the kitty termianl titlebar updates but its fairly quick compare to latptop.
While it is happening kitty terminal tital bar is keep updating text. Video is attached here, but please note that video is not justifying what I am seeing here. In actual scenarious kitty termianl's title bar is keep flashing new data and its about 10-20 updates per seconds.
cinnamon-2022-10-30T132359-0400.webm
Which version of Neovim are you using?
Neovim 0.8.0
To Reproduce
Steps to reproduce the behavior (I believe its happens only on slow hardware):

Get a slow hardware (or trottle the lsp progress in some way)
fire up the LSP server
see the titlebar updated till done with LSP progress bar (loading workspace and diagnosing workspace)

Expected Behavior
keep the titlebar name to opened filename only not to noice messages scrollbar (noice://<some number>) from loading workspace or diagnosing workspace LSP progress.
Noice Log
Please include any related errors from the Noice log file. (open with :Noice log)

Noice log
It was empty!

**Comment by folke** [comment] 2022-11-07 07:14
Duplicate of #197

**Closed by folke** 2022-11-07 07:14 UTC
Labels: bug
