### ISSUE TITLE
bug: "n fewer lines" message appears twice when deleting lines in visual-line mode

### ISSUE THREAD

**Issue by gracepetryk** [folke/noice.nvim#442] opened 2023-04-26 04:19 UTC
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

MacOS 13.3.1

### Describe the bug

When deleting multiple lines in visual-line mode, the "n fewer lines" message displays twice
![image](https://user-images.githubusercontent.com/5047809/234467793-2bdb6548-c104-4022-8b43-f5bea104b4af.png)

This is despite the message only appearing once in `:messages`:
![image](https://user-images.githubusercontent.com/5047809/234468464-9faae67e-5ef7-4353-a50d-afd551d71e8e.png)

### Steps To Reproduce

1. Enter visual line mode
2. Delete at least 3 lines with 'd'

### Expected Behavior

The "n fewer lines" message only appears one time.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
  "MunifTanjim/nui.nvim",
    -- OPTIONAL:
    --   `nvim-notify` is only needed, if you want to use the notification view.
    --   If not available, we use `mini` as the fallback
    "rcarriga/nvim-notify",
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

require('noice').setup({})
```

**Comment by MariaSolOs** [comment] 2023-07-04 05:16
I don't think this is exclusive to visual-line mode. I'm seeing it happen with a simple `dd`.

**Comment by folke** [comment] 2023-07-04 06:51
Duplicate messages are actually due to a [Neovim bug](https://github.com/neovim/neovim/issues/20416).

Noice literally gets hundreds of duplicate messages all the time.

There's special handling to prevent most duplicates, but some like these probably slip through.

Having said that, I can't reproduce this on nightly. It only happens on stable, so whatever is causing this has already been fixed on nightly it seems.

**Closed by folke** 2023-07-04 06:51 UTC
Labels: bug
